/**
 * 排班管理服务
 */

import { get, post, put, del } from './request';

export interface Schedule {
  id: string;
  planId?: string;
  employeeId: string;
  date: Date;
  shiftType: 'NORMAL' | 'OVERTIME' | 'REST' | 'LEAVE';
  startTime?: string;
  endTime?: string;
  status: 'SCHEDULED' | 'CONFIRMED' | 'COMPLETED' | 'CANCELLED';
  assignedCapacity?: number;
  skillMatch?: number;
  isAutoGenerated?: boolean;
  generatedAt?: Date;
  adjustedBy?: string;
  adjustedAt?: Date;
  remark?: string;
  employee?: {
    name: string;
    employeeId: string;
    position: string;
    department?: { name: string };
  };
  plan?: {
    productName: string;
    targetQty: number;
  };
}

export interface ScheduleFilter {
  factoryId?: string;
  departmentId?: string;
  startDate?: string;
  endDate?: string;
  employeeId?: string;
}

export interface GenerateScheduleParams {
  factoryId: string;
  startDate: string;
  endDate: string;
  departmentId?: string;
  planId?: string;
}

const scheduleAPI = {
  /**
   * 获取排班列表
   */
  async getSchedules(params: ScheduleFilter) {
    try {
      const data = await get('/schedules', params);
      return data;
    } catch (error) {
      console.error('获取排班列表失败:', error);
      throw error;
    }
  },

  /**
   * 获取排班统计
   */
  async getStats(params: { factoryId: string; startDate: string; endDate: string }) {
    try {
      const data = await get('/schedules/stats', params);
      return data;
    } catch (error) {
      console.error('获取排班统计失败:', error);
      throw error;
    }
  },

  /**
   * 创建排班
   */
  async createSchedule(data: Partial<Schedule>) {
    try {
      const result = await post('/schedules', data);
      return result;
    } catch (error) {
      console.error('创建排班失败:', error);
      throw error;
    }
  },

  /**
   * 批量创建排班
   */
  async batchCreate(schedules: Partial<Schedule>[]) {
    try {
      const data = await post('/schedules/batch', { schedules });
      return data;
    } catch (error) {
      console.error('批量创建排班失败:', error);
      throw error;
    }
  },

  /**
   * AI智能生成排班
   */
  async generateSchedule(params: GenerateScheduleParams) {
    try {
      const data = await post('/schedules/generate', params);
      return data;
    } catch (error: any) {
      console.error('AI排班生成失败:', error);
      throw error;
    }
  },

  /**
   * 更新排班
   */
  async updateSchedule(id: string, data: Partial<Schedule>) {
    try {
      const result = await put(`/schedules/${id}`, data);
      return result;
    } catch (error) {
      console.error('更新排班失败:', error);
      throw error;
    }
  },

  /**
   * 删除排班
   */
  async deleteSchedule(id: string) {
    try {
      const data = await del(`/schedules/${id}`);
      return data;
    } catch (error) {
      console.error('删除排班失败:', error);
      throw error;
    }
  },

  /**
   * 处理请假变动
   */
  async handleLeaveChange(leaveApplicationId: string) {
    try {
      const data = await post('/schedules/handle-leave', {
        leaveApplicationId,
      });
      return data;
    } catch (error) {
      console.error('处理请假变动失败:', error);
      throw error;
    }
  },
};

export default scheduleAPI;
